# Basic NumPy Operations

In [3]:
import numpy as np

nd_arr = np.array([1, 2, 3, 4, 5])
print(nd_arr.ndim) # number of dimensions
print(nd_arr.shape) # rows, columns
print(nd_arr.size)  # total number of elements
print(nd_arr.dtype)

1
(5,)
5
int64


In [5]:
typed_arr = np.array([1, 2.5, 3, 4.3, 5], dtype=int)
print(typed_arr)

[1 2 3 4 5]


## ND Array creation

In [13]:
list_arr = np.array([1, 2, 3, 4, 5])
print("from list:", list_arr)
tuple_arr = np.array((1, 2, 3, 4, 5))
print("from tuple:", tuple_arr)
zeros_arr = np.zeros((3, 4))
print("zeros array:\n", zeros_arr)
ones_arr = np.ones((2, 5))
print("ones array:\n", ones_arr)
range_arr = np.arange(10, 21, 2)
print("arange array:", range_arr)
linspace_arr = np.linspace(0, 1, 5)
print("linspace array:", linspace_arr)

from list: [1 2 3 4 5]
from tuple: [1 2 3 4 5]
zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
arange array: [10 12 14 16 18 20]
linspace array: [0.   0.25 0.5  0.75 1.  ]


In [17]:
print(np.random.rand(3, 3))  # 3x3 array with random floats in [0.0, 1.0]
print(np.random.randint(1, 10, (4, 4)))  # 4x4 array with random ints in [1, 10]

[[0.25752829 0.38655818 0.58671146]
 [0.41509825 0.51682641 0.82382475]
 [0.86820695 0.53172524 0.67970616]]
[[7 1 5 9]
 [3 3 2 8]
 [6 9 7 7]
 [2 4 9 6]]


In [5]:
import numpy as np
print("identity matrix\n", np.eye(3))
print("diagonal: \n", np.diag([1, 2, 3]))

identity matrix
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diagonal: 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [14]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])

for x in np.nditer(arr):
    print(x, end=' ')

[2 3 4]
1 2 3 4 5 